service: contactRelayMessage

package:
  exclude:
    - ./**
  include:
    - ./relay.js
    - ./apiGateway/DefaultSockets.js

provider:
  name: aws
  stage: prod
  runtime: nodejs12.x
  region: us-east-1
  timeout: 3
  memorySize: 256
  environment:
    DM_WH: ${env:DM_WH}
    ENDPOINT_ROUTE: ${env:ENDPOINT_ROUTE}
    HOST_EMAIL: ${env:HOST_EMAIL}

functions:
  connect:
    description: 'adds connected users to db'
    handler: api/DefaultSockets.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    description: 'removes disconnected users from db'
    handler: api/DefaultSockets.disconnect
    events:
      - websocket:
          route: $disconnect
  default:
    description: 'handles unhandled routes'
    handler: api/DefaultSockets.default
    events:
      - websocket:
          route: $default
  GetAvail:
    description: 'Allows client to get up to date on host availability'
    handler: api/availability.GetAvail
    events:
      - websocket:
          route: GetAvail
  login:
    description: 'request to log into service'
    handler: api/authentication.login
    events:
      - websocket:
          route: login
  ice:
    description: 'Exchange ice candidates'
    handler: api/WebRTC.ice
    events:
      - websocket:
          route: ice
  offer:
    description: 'Offer SDP negotiation data to host'
    handler: api/WebRTC.offer
    events:
      - websocket:
          route: offer
  answer:
    description: 'Answer from host with SPD data'
    handler: api/WebRTC.answer
    events:
      - websocket:
          route: answer
  relay:
    description: 'Relays messages from contact form to slack'
    handler: api/slackDM.relay
    events:
      - websocket:
          route: relay
