service: contactRelayMessage

package:
  exclude:
    - ./**
  include:
    - ./relay.js
    - ./apiGateway/DefaultSockets.js

provider:
  name: aws
  stage: prod
  runtime: nodejs12.x
  region: us-east-1
  timeout: 3
  memorySize: 256
  environment:
    DM_WH: ${env:DM_WH}

functions:
  connect:
    description: 'adds connected users to db'
    handler: apiGateway/DefaultSockets.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    description: 'removes disconnected users from db'
    handler: apiGateway/DefaultSockets.disconnect
    events:
      - websocket:
          route: $disconnect
  default:
    description: 'handles unhandled routes'
    handler: apiGateway/DefaultSockets.default
    events:
      - websocket:
          route: $default
  slack:
    handler: relay.slack
    events:
      - http:
          path: dm
          method: POST
          cors:
            origins:
              - 'https://${env:BUCKET_NAME}'
